# Generated by Django 2.0.5 on 2018-05-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quizzes'},
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='wtf1', max_length=20),
            preserve_default=False,
        ),
    ]
