# Generated by Django 2.0.5 on 2018-05-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20180510_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'choice_text')},
        ),
    ]
